- name: Deploy a website on local web server
  hosts: local
  become: yes

  tasks:
    - name: Installing Apache
      apt:
        name: apache2
        state: present

    - name: Starting Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Installing wget
      apt:
        name: wget
        state: present

    - name: Download the website zip file
      get_url:
        url: https://www.free-css.com/assets/files/free-css-templates/download/page290/digimedia.zip
        dest: /tmp/digimedia.zip

    - name: Installing unzip tool
      apt:
        name: unzip
        state: present

    - name: Clean up default Apache web directory
      file:
        path: /var/www/html
        state: absent

    - name: Recreate Apache web directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Unzip the website directly to Apache web root
      unarchive:
        src: /tmp/digimedia.zip
        dest: /tmp/
        remote_src: yes
    - name: Copy the website files to Apache web root (only contents)
      copy:
        src: /tmp/templatemo_568_digimedia/
        dest: /var/www/html/
        remote_src: yes
    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted
    - name: Site hosted on..........
      debug:
        msg: "Server is running at http://localhost:{{ server_port | default('80')}}"
        